[tools]
node = 'lts'
java = "zulu-17.42.19"
usage = "latest"
maven = "3"
bun = "latest"
pnpm = "latest"
gh = "latest"
awscli = "latest"
pipx = "latest"
jq = "latest"
yq = "latest"
python = "3.14"
#  Fix rg permissiosn. See https://github.com/anthropics/claude-code/issues/41463
claude = { version = "latest", postinstall = "chmod +x $MISE_TOOL_INSTALL_PATH/lib/node_modules/@anthropic-ai/claude-code/vendor/ripgrep/*/rg" }
"npm:@google/gemini-cli" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:mcp-hub" = "latest"
"npm:@github/copilot" = "latest"
"npm:typescript" = "latest"
"npm:@zed-industries/claude-agent-acp" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
