[tools]
node = 'lts'
java = "zulu-17.42.19"
usage = "latest"
maven = "3"
bun = "latest"
pnpm = "latest"
gh = "latest"
awscli = "latest"
pipx = "latest"
jq = "latest"
yq = "latest"
python = "3.14"
"npm:tree-sitter-cli" = "latest"
"npm:mcp-hub" = "latest"
"npm:@github/copilot" = "latest"
"npm:typescript" = "6.0.3"
"npm:@zed-industries/claude-agent-acp" = "latest"
"aqua:ankitpokhrel/jira-cli" = "latest"
antigravity-cli = "latest"

[tools.claude]
version = "latest"
minimum_release_age = "0s"

[settings]
idiomatic_version_file_enable_tools = ["node"]
