theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "net"
format = "{speed_down;K} {speed_up;K}"
format_alt = "{signal_strength} {bitrate} {ip}"

[[block]]
block = "sound"
device_kind = "sink"
on_click = "pavucontrol"

[[block]]
block = "sound"
device_kind = "source"
on_click = "pavucontrol"

[[block]]
block = "time"
# https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html#specifiers
format = "%Y-%m-%d %k:%M"
on_click = "gnome-calendar"
