icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#3c3846"
idle_fg = "#ebdbb2"
good_bg = "#b8bb26"
good_fg = "#282828"
critical_bg = "#cc241d"
critical_fg = "#282828"
warning_bg = "#fabd2f"
warning_fg = "#282828"
info_bg = "#83a598"
info_fg = "#282828"
alternating_tint_bg = "#080808"

[[block]]
block = "memory"
format_mem = "$mem_used.eng(3,B,M)/$mem_total.eng(3,B,M)($mem_used_percents.eng(2))"
format_swap = "$swap_used.eng(3,B,M)/$swap_total.eng(3,B,M)($swap_used_percents.eng(2))"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1

[[block]]
block = "music"
format = "$combo.rot-str(25) $play $next|"

[[block]]
block = "battery"
format = "$percentage $time|$percentage"

[[block]]
block = "sound"
device_kind = "sink"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
device_kind = "source"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
# https://docs.rs/chrono/0.4.19/chrono/format/strftime/index.html#specifiers
format = "%Y-%m-%d %k:%M"
[[block.click]]
button = "left"
cmd = "gnome-calendar"
