"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[time]
disabled = false

[git_metrics]
disabled = false

[directory]
# NOTE: show more directory levels than the default 3
truncation_length = 8

[aws]
disabled = true
